version: '3.8'

services:
  frontend:
    container_name: proyecto-gestion-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge