services:
  db:
    image: postgres:16
    container_name: db_siexud_new
    environment:
      POSTGRES_PASSWORD: qZVmQxZPE532qu39gGoH7F1DqrbUlW
      POSTGRES_USER: admin
      POSTGRES_DB: nuevo_siexud
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: proyecto-gestion-backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_DB: nuevo_siexud
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qZVmQxZPE532qu39gGoH7F1DqrbUlW
      PORT: 8000
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: proyecto-gestion-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge