services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: proyecto-gestion-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    # Si PostgreSQL está en TU MÁQUINA (localhost), usa esto:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Si está en OTRA máquina, borra extra_hosts y pon la IP en .env
    networks:
      - app_network
      - docker-wordpress_mynet
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: proyecto-gestion-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - app_network
      - docker-wordpress_mynet
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
  docker-wordpress_mynet:
    driver: bridge