services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: proyecto-gestion-backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db_siexud_new
      DB_PORT: 5432
      POSTGRES_DB: nuevo_siexud
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qZVmQxZPE532qu39gGoH7F1DqrbUlW
      PORT: 8000
      NODE_ENV: production
    extra_hosts:
      - "db_siexud_new:host-gateway"  # Esto permite la conexión al PostgreSQL externo
    networks:
      - app_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: proyecto-gestion-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge